name: Dummy GitHub Action Workflow

on:
  push:
    branches:
      - main

jobs:
  dummy_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a dummy command
        run: |
          echo "This is a dummy GitHub Actions workflow."
          echo "You can replace this with your actual workflow steps."
